// F8 AI features: AI-01..08 (plan .plans/e2e-scenarios.md, "F8 AI features").
//
// Every model call goes to the provider stub's OpenAI-compatible endpoint
// (OPENAI_BASE_URL = <stub>/openai/v1, GEMINI_API_KEY blank; lib/ai.ts
// createClient). The stub picks a fixture by keyword in the last user message
// (support/provider-stub/server.mjs pickFixtureName) or by a forced rule.
//
// Verified against the code:
// - /app/ai-invoice (AIInvoicePrompt + AIInvoicePreview): textarea under
//   "Instruksi AI", submit "Generate draft" -> POST /api/invoices/ai. 200 ->
//   AIInvoicePreview renders InvoiceFormClient ("Review draft invoice") prefilled
//   with the draft; any non-OK -> role=alert with body.error ("Invalid AI
//   response") and the empty fallback form. The route parses the first {...}
//   of the completion with AIInvoiceSchema; a parse failure or a provider
//   error is a 400 { error: "Invalid AI response", fallback }.
// - /app/insight (server page builds the summary, InsightClient POSTs it to
//   /api/ai/invoice-insight on mount). The route answers 200 { data, fallback }
//   either way; fallback true renders "Insight menampilkan data fallback ...".
//   The prompt contains "analis finansial" (insight fixture) and the summary
//   JSON (client names).
// - /app/settings/theme (ThemeSettingsPanel): "Dapatkan Saran AI" -> POST
//   /api/ai/theme-suggest { brandName, preferredMode } -> applyAiTheme (not
//   persisted) and shows the label/description; the hex labels next to the
//   colour inputs show the applied palette. Prompt contains "palet warna".
// - /app/receipts/scan (ReceiptScanner): a hidden <input type=file
//   accept=image/*>; the file is read as a data URL and POSTed to
//   /api/receipts/ai-scan as { image }; the route sends it as an image_url part
//   (stub -> receipt-scan fixture). Success shows "Data berhasil diekstrak!" and
//   the prefilled "Review draft invoice" form.
// - AI-06: the OpenAI SDK (openai 4.x) retries 503 twice (maxRetries 2), so
//   the stub is forced to 503 for 3 calls; the spec asserts on the first
//   request and tolerates 1..3 recorded calls.
// - AI-07: POST /api/ai/explain is platform-admin only (401/403 covered by
//   SEC-12) and takes { recommendation_id } of an existing OptimizationLog.
//   No app route creates OptimizationLog rows, so the DB seed
//   (support/db/seed-platform-admin.mjs) adds one APPLIED row with the fixed id
//   below. GET /api/ai-optimizer/recommendations is public and lists PENDING
//   rows as { route, confidence } only; it reads the DB, never PostHog
//   (POSTHOG_API_KEY is blank, so the stub's /posthog host sees no call).
// - AI-08: GET /api/ai/orchestrator and /devtools/ai-agents are platform-admin
//   only; ENABLE_AI_ORCHESTRATION=memory keeps the stream in process.
import type { Page } from "@playwright/test";

import { expect, test, type StubRequest } from "../../fixtures";
import { InvoiceFormPage } from "../../pages/InvoiceFormPage";
import type { InvoiceRecord } from "../../support/api-factories";

const covers = (...routes: string[]) => routes.map((description) => ({ type: "covers", description }));

const tag = () => `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;

const COMPLETIONS = "/openai/v1/chat/completions";

// Keep in sync with E2E_AI_RECOMMENDATION_ID in support/db/seed-platform-admin.mjs.
const E2E_AI_RECOMMENDATION_ID = "e2e-ai07-recommendation";

// Canned fixtures (support/provider-stub/fixtures/*.json).
const DRAFT = {
  client: "Acme Stub Co",
  items: [
    { name: "Website design", qty: 2, price: 150_000 },
    { name: "Hosting (annual)", qty: 1, price: 500_000 },
  ],
  notes: "Generated by the e2e provider stub",
};
const RECEIPT_SCAN = {
  client: "Toko Stub Mart",
  items: [
    { name: "Kertas A4", qty: 3, price: 45_000 },
    { name: "Tinta printer", qty: 1, price: 120_000 },
  ],
  notes: "Receipt scanned by the e2e provider stub",
};
const INSIGHT = {
  totalRevenue: "Rp 12.345.000",
  topClient: "Acme Stub Co",
  insight: "Canned stub insight: pendapatan stabil dengan sebagian besar invoice sudah dibayar.",
  recommendation: "Canned stub recommendation: tawarkan diskon early payment kepada klien utama.",
};
const THEME = {
  primary: "#0F766E",
  accent: "#F59E0B",
  label: "Stub Teal",
  description: "Canned teal and amber palette from the e2e provider stub.",
};
const EXPLAIN = {
  why: "Canned stub explanation: perubahan ini mengurangi LCP pada rute terkait.",
  context: "Dihasilkan oleh e2e provider stub.",
  dataBasis: ["p95 LCP 3.1s", "INP 240ms"],
  confidence: 0.82,
};

/** A 1x1 transparent PNG, created in-test (no binary fixture file). */
const TINY_PNG = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
  "base64",
);

/** Text of the last user message the app sent to the stub (string or multi-part content). */
function lastUserContent(request: StubRequest): { text: string; parts: Array<{ type?: string; image_url?: { url?: string } }> } {
  const body = request.json as { messages?: Array<{ role: string; content: unknown }> } | undefined;
  const user = [...(body?.messages ?? [])].reverse().find((message) => message.role === "user");
  if (typeof user?.content === "string") return { text: user.content, parts: [] };
  const parts = Array.isArray(user?.content) ? (user.content as Array<{ type?: string; text?: string; image_url?: { url?: string } }>) : [];
  return { text: parts.filter((part) => part.type === "text").map((part) => part.text ?? "").join("\n"), parts };
}

const aiPrompt = (page: Page) => page.getByRole("textbox").first();
const generateButton = (page: Page) => page.getByRole("button", { name: "Generate draft" });
const reviewHeading = (page: Page) => page.getByRole("heading", { name: "Review draft invoice" });

async function listInvoiceIds(api: { get(url: string): Promise<import("@playwright/test").APIResponse> }): Promise<string[]> {
  const response = await api.get("/api/invoices");
  expect(response.status()).toBe(200);
  const body = (await response.json()) as { data: InvoiceRecord[] };
  return body.data.map((invoice) => invoice.id);
}

test.describe("AI invoice composer (/app/ai-invoice)", () => {
  test.slow();

  test(
    "AI-01 a prompt is sent to the model, the draft prefills the form, and saving creates the invoice",
    { annotation: covers("/app/ai-invoice", "/api/invoices/ai", "/api/invoices") },
    async ({ isolatedUser, stub }) => {
      const { page } = isolatedUser;
      const prompt = `AI-01 ${tag()}: buat invoice desain website 2x dan hosting tahunan untuk Acme`;

      await page.goto("/app/ai-invoice");
      await expect(page.getByRole("heading", { name: "Buat draft invoice dari perintah natural language" })).toBeVisible();
      await aiPrompt(page).fill(prompt);
      const generated = page.waitForResponse(
        (r) => new URL(r.url()).pathname === "/api/invoices/ai" && r.request().method() === "POST",
      );
      await generateButton(page).click();
      expect((await generated).status()).toBe(200);

      const calls = await stub.requests(COMPLETIONS);
      expect(calls).toHaveLength(1);
      expect(calls[0].method).toBe("POST");
      expect(lastUserContent(calls[0]).text).toBe(prompt);

      await expect(reviewHeading(page)).toBeVisible();
      const form = new InvoiceFormPage(page);
      await expect(form.client).toHaveValue(DRAFT.client);
      await expect(form.notes).toHaveValue(DRAFT.notes);
      for (const [index, item] of DRAFT.items.entries()) {
        await expect(form.itemName(index)).toHaveValue(item.name);
        await expect(form.itemQty(index)).toHaveValue(String(item.qty));
        await expect(form.itemPrice(index)).toHaveValue(String(item.price));
      }

      const created = page.waitForResponse(
        (r) => new URL(r.url()).pathname === "/api/invoices" && r.request().method() === "POST",
      );
      await form.saveDraft();
      const response = await created;
      expect(response.status()).toBe(201);
      const { data: invoice } = (await response.json()) as { data: InvoiceRecord };
      const subtotal = DRAFT.items.reduce((sum, item) => sum + item.qty * item.price, 0);
      expect(invoice).toMatchObject({ client: DRAFT.client, status: "DRAFT", subtotal, notes: DRAFT.notes });
      expect(invoice.items).toHaveLength(DRAFT.items.length);
      await expect(page).toHaveURL(new RegExp(`/app/invoices/${invoice.id}$`));
      expect(await listInvoiceIds(isolatedUser.api)).toContain(invoice.id);
    },
  );

  test(
    "AI-02 a malformed completion shows a visible error and creates no invoice",
    { annotation: covers("/app/ai-invoice", "/api/invoices/ai") },
    async ({ isolatedUser, stub }) => {
      const { page, api } = isolatedUser;
      const before = await listInvoiceIds(api);

      await page.goto("/app/ai-invoice");
      // "malformed" in the prompt selects the completion-malformed fixture.
      await aiPrompt(page).fill(`AI-02 ${tag()} malformed draft please`);
      const generated = page.waitForResponse(
        (r) => new URL(r.url()).pathname === "/api/invoices/ai" && r.request().method() === "POST",
      );
      await generateButton(page).click();
      const response = await generated;
      expect(response.status()).toBe(400);
      expect(await response.json()).toMatchObject({ error: "Invalid AI response", fallback: { client: "" } });

      await expect(page.getByRole("alert").filter({ hasText: "Invalid AI response" })).toBeVisible();
      expect(await stub.requests(COMPLETIONS)).toHaveLength(1);
      // The empty fallback form is shown for manual entry; nothing was saved.
      await expect(new InvoiceFormPage(page).client).toHaveValue("");
      expect(await listInvoiceIds(api)).toEqual(before);
    },
  );

  test(
    "AI-06 the model answering 503 surfaces an error in the UI within 20 s (no hang)",
    { annotation: covers("/app/ai-invoice", "/api/invoices/ai") },
    async ({ isolatedUser, stub }) => {
      const { page, api } = isolatedUser;
      const before = await listInvoiceIds(api);
      // 1 call + the OpenAI SDK's 2 default retries.
      await stub.force({ target: COMPLETIONS, status: 503, count: 3 });

      await page.goto("/app/ai-invoice");
      await aiPrompt(page).fill(`AI-06 ${tag()}: invoice konsultasi 1 juta`);
      const started = Date.now();
      await generateButton(page).click();
      await expect(page.getByRole("alert").filter({ hasText: "Invalid AI response" })).toBeVisible({ timeout: 20_000 });
      const elapsed = Date.now() - started;
      expect(elapsed, `UI error after ${elapsed} ms`).toBeLessThan(20_000);
      await expect(generateButton(page)).toBeEnabled();

      const calls = await stub.requests(COMPLETIONS);
      expect(calls.length).toBeGreaterThanOrEqual(1);
      expect(calls.length).toBeLessThanOrEqual(3);
      expect(calls[0].method).toBe("POST");
      expect(lastUserContent(calls[0]).text).toContain("AI-06");
      expect(await listInvoiceIds(api)).toEqual(before);
    },
  );
});

test.describe("AI insight, theme and receipt scan", () => {
  test.slow();

  test(
    "AI-03 /app/insight sends the workspace summary to the model and renders the canned insight",
    { annotation: covers("/app/insight", "/api/ai/invoice-insight") },
    async ({ isolatedUser, stub }) => {
      const { page, factory } = isolatedUser;
      const client = `AI-03 client ${tag()}`;
      await factory.createInvoice({ client, status: "SENT" });

      const insight = page.waitForResponse(
        (r) => new URL(r.url()).pathname === "/api/ai/invoice-insight" && r.request().method() === "POST",
      );
      await page.goto("/app/insight");
      await expect(page.getByRole("heading", { name: "AI Invoice Insights", level: 1 })).toBeVisible();
      const response = await insight;
      expect(response.status()).toBe(200);
      expect(await response.json()).toEqual({ data: INSIGHT, fallback: false });

      await expect(page.getByText(INSIGHT.totalRevenue, { exact: true })).toBeVisible();
      await expect(page.getByText(INSIGHT.insight)).toBeVisible();
      await expect(page.getByText(INSIGHT.recommendation)).toBeVisible();
      await expect(page.getByText(`Klien utama: ${INSIGHT.topClient}`)).toBeVisible();
      await expect(page.getByText("Insight menampilkan data fallback")).toHaveCount(0);

      const calls = await stub.requests(COMPLETIONS);
      expect(calls).toHaveLength(1);
      const sent = lastUserContent(calls[0]).text;
      expect(sent).toContain("analis finansial");
      expect(sent).toContain(client);
    },
  );

  test(
    "AI-04 'Dapatkan Saran AI' on /app/settings/theme applies the canned palette",
    { annotation: covers("/app/settings/theme", "/api/ai/theme-suggest") },
    async ({ isolatedUser, stub }) => {
      const { page, user } = isolatedUser;
      await page.goto("/app/settings/theme");
      await expect(page.getByRole("heading", { name: "Theme Settings" })).toBeVisible();

      const suggested = page.waitForResponse(
        (r) => new URL(r.url()).pathname === "/api/ai/theme-suggest" && r.request().method() === "POST",
      );
      await page.getByRole("button", { name: "Dapatkan Saran AI" }).click();
      const response = await suggested;
      expect(response.status()).toBe(200);
      expect(await response.json()).toEqual({
        data: { ...THEME, primary: THEME.primary.toLowerCase(), accent: THEME.accent.toLowerCase() },
        cached: false,
      });

      // The hex labels next to the colour inputs show the applied palette.
      await expect(page.getByLabel("Pilih warna utama")).toHaveValue(THEME.primary.toLowerCase());
      await expect(page.getByLabel("Pilih warna aksen")).toHaveValue(THEME.accent.toLowerCase());
      await expect(page.getByText(THEME.primary, { exact: true })).toBeVisible();
      await expect(page.getByText(THEME.accent, { exact: true })).toBeVisible();
      await expect(page.getByText(THEME.description)).toBeVisible();
      await expect(page.getByRole("button", { name: `Apply ${THEME.label} theme` })).toBeVisible();
      await expect(page.getByRole("button", { name: "Simpan Tema" })).toBeEnabled();

      const calls = await stub.requests(COMPLETIONS);
      expect(calls).toHaveLength(1);
      const sent = lastUserContent(calls[0]).text;
      expect(sent).toContain("palet warna");
      expect(sent).toContain(user.name);
    },
  );

  test(
    "AI-05 uploading a receipt image on /app/receipts/scan prefills the draft form with the canned extraction",
    { annotation: covers("/app/receipts/scan", "/api/receipts/ai-scan") },
    async ({ isolatedUser, stub }) => {
      const { page } = isolatedUser;
      await page.goto("/app/receipts/scan");
      await expect(page.getByRole("heading", { name: "Pindai Struk dengan AI" })).toBeVisible();

      const scanned = page.waitForResponse(
        (r) => new URL(r.url()).pathname === "/api/receipts/ai-scan" && r.request().method() === "POST",
      );
      await page.locator('input[type="file"]').setInputFiles({
        name: "receipt.png",
        mimeType: "image/png",
        buffer: TINY_PNG,
      });
      const response = await scanned;
      expect(response.status()).toBe(200);

      await expect(page.getByRole("heading", { name: "Data berhasil diekstrak!" })).toBeVisible();
      await expect(reviewHeading(page)).toBeVisible();
      const form = new InvoiceFormPage(page);
      await expect(form.client).toHaveValue(RECEIPT_SCAN.client);
      await expect(form.notes).toHaveValue(RECEIPT_SCAN.notes);
      for (const [index, item] of RECEIPT_SCAN.items.entries()) {
        await expect(form.itemName(index)).toHaveValue(item.name);
        await expect(form.itemQty(index)).toHaveValue(String(item.qty));
        await expect(form.itemPrice(index)).toHaveValue(String(item.price));
      }

      const calls = await stub.requests(COMPLETIONS);
      expect(calls).toHaveLength(1);
      const image = lastUserContent(calls[0]).parts.find((part) => part.type === "image_url");
      expect(image?.image_url?.url).toBe(`data:image/png;base64,${TINY_PNG.toString("base64")}`);
    },
  );
});

test.describe("AI governance and orchestration (platform admin)", () => {
  test(
    "AI-07 POST /api/ai/explain returns the canned explanation; GET /api/ai-optimizer/recommendations lists { route, confidence } only",
    { annotation: covers("/api/ai/explain", "/api/ai-optimizer/recommendations") },
    async ({ persona, api, stub }) => {
      const admin = await persona("platformAdmin");

      const explained = await admin.api.post("/api/ai/explain", { data: { recommendation_id: E2E_AI_RECOMMENDATION_ID } });
      expect(explained.status()).toBe(200);
      const { data } = (await explained.json()) as { data: Record<string, unknown> };
      expect(data).toMatchObject({
        recommendationId: E2E_AI_RECOMMENDATION_ID,
        route: "/app/insight",
        ...EXPLAIN,
      });
      expect(typeof data.id).toBe("string");
      expect(typeof data.trustScore).toBe("number");

      const calls = await stub.requests(COMPLETIONS);
      expect(calls).toHaveLength(1);
      const sent = lastUserContent(calls[0]).text;
      expect(sent).toContain("AI governance explainer");
      expect(sent).toContain('"route": "/app/insight"');

      // An unknown recommendation id is a 400 and never reaches the model.
      await stub.reset();
      const unknown = await admin.api.post("/api/ai/explain", { data: { recommendation_id: `missing-${tag()}` } });
      expect(unknown.status()).toBe(400);
      expect(await stub.requests(COMPLETIONS)).toHaveLength(0);

      // Public list: PENDING OptimizationLog rows reduced to { route, confidence }.
      const listed = await api.get("/api/ai-optimizer/recommendations");
      expect(listed.status()).toBe(200);
      const body = (await listed.json()) as { recommendations: Array<Record<string, unknown>> };
      expect(Object.keys(body)).toEqual(["recommendations"]);
      expect(Array.isArray(body.recommendations)).toBe(true);
      for (const entry of body.recommendations) {
        expect(Object.keys(entry).sort()).toEqual(["confidence", "route"]);
        expect(typeof entry.route).toBe("string");
        expect(typeof entry.confidence).toBe("number");
      }
      // The seeded row is APPLIED, so it is not offered for prefetching.
      expect(body.recommendations.map((entry) => entry.route)).not.toContain("/app/insight");
      // The list reads the DB only; no PostHog query reaches the stubbed host.
      expect(await stub.requests("/posthog")).toHaveLength(0);
    },
  );

  test(
    "AI-08 GET /api/ai/orchestrator returns the snapshot and /devtools/ai-agents renders it",
    { annotation: covers("/api/ai/orchestrator", "/devtools/ai-agents") },
    async ({ persona }) => {
      const admin = await persona("platformAdmin");

      const snapshotResponse = await admin.api.get("/api/ai/orchestrator");
      expect(snapshotResponse.status()).toBe(200);
      expect(snapshotResponse.headers()["cache-control"]).toBe("no-store");
      const snapshot = (await snapshotResponse.json()) as {
        enabled: boolean;
        agents: Array<{ agentId: string; name: string; priority: number }>;
        events: Array<{ traceId: string; type: string; source: string }>;
        conflicts: unknown[];
        lastUpdated: string;
      };
      expect(snapshot.enabled).toBe(true);
      expect(Array.isArray(snapshot.agents)).toBe(true);
      expect(Array.isArray(snapshot.events)).toBe(true);
      expect(Array.isArray(snapshot.conflicts)).toBe(true);
      expect(Number.isNaN(Date.parse(snapshot.lastUpdated))).toBe(false);

      const { page } = admin;
      await page.goto("/devtools/ai-agents");
      await expect(page).toHaveURL(/\/devtools\/ai-agents$/);
      await expect(page.getByRole("heading", { name: "AI Agent Orchestration", level: 1 })).toBeVisible();
      await expect(page.getByRole("heading", { name: "Multi-agent orchestration" })).toBeVisible();
      await expect(page.getByText("Visualisasi hubungan antar agen dan aktivitas event stream AI.")).toBeVisible();
      await expect(page.getByRole("heading", { name: /^Log terbaru \(\d+\)$/ })).toBeVisible();
      await expect(page.getByRole("heading", { name: "Trace audit" })).toBeVisible();
      // The page reads the same in-process registry and stream as the API.
      for (const agent of snapshot.agents) {
        await expect(page.getByText(agent.name, { exact: true }).first()).toBeVisible();
      }
      if (snapshot.events.length === 0) {
        await expect(page.getByText("Belum ada event yang terekam untuk filter saat ini.")).toBeVisible();
      }
    },
  );
});
